### ISSUE TITLE
python-pltable: Stable release available (v1.0.2), no longer conflicts python-prettytable

### ISSUE THREAD

**Issue by ghost** [saruman9/pkgbuilds#1]
I know that the PKGBUILD is for `python-pltable-git`, but now a stable release [v1.0.2 is available](https://pypi.org/project/PLTable/) so a `python-pltable` package can be created.
In addition, in v1.0.2, the name in the code has been changed from `prettytable` to `pltable`, so `conflicts=('python-prettytable')` can probably be removed.

**Comment by saruman9** [comment]
Thank you for information about stable version of PLTable! Fixed by c645702bf8e6e953fffed37f4e4f7c562ac24213.
